POST http://localhost:8080/accounts
Content-Type: application/json

{
  "document_number": "12345678900"
}

###
POST http://localhost:8080/accounts
Content-Type: application/json

{
}


###

GET http://localhost:8080/accounts/1
Content-Type: application/json

###

GET http://localhost:8080/accounts/2
Content-Type: application/json