### Criação de uma transação, passando os dados da conta, o tipo de operação e o montante.
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "account_id": 1,
  "operation_type_id": 2,
  "amount": 123.45
}


### Tentativa de criação de uma conta, sem informação, para verificação de erro.
POST http://localhost:8080/transactions
Content-Type: application/json

{}