server:
  error:
    include-message: always
spring:
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost/demoapp}
    username: ${POSTGRESQL_USERNAME:demoapp}
    password: ${POSTGRESQL_PASSWORD:demoapp}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration/dev
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost/demoapp}
    user: ${POSTGRESQL_USERNAME:demoapp}
    password: ${POSTGRESQL_PASSWORD:demoapp}
    baselineOnMigrate: true