server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost/demoapp
    username: demoapp
    password: demoapp
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration/dev
    url: jdbc:postgresql://localhost/demoapp
    user: demoapp
    password: demoapp
    baselineOnMigrate: true